# Generated by Django 3.0.8 on 2021-03-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=10)),
                ('Scheme', models.CharField(max_length=10)),
                ('Scheme_Amount', models.CharField(max_length=10)),
                ('Maturity_Amount', models.CharField(max_length=20)),
                ('Maturity_Period', models.CharField(max_length=10)),
            ],
        ),
    ]
