# Generated by Django 3.0.8 on 2021-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='Policy',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
