# Generated by Django 3.0.8 on 2021-03-19 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('Appl_Id', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Father', models.CharField(max_length=50)),
                ('Mother', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=10)),
                ('Qual', models.CharField(max_length=10)),
                ('Mobile', models.CharField(max_length=15)),
                ('Aadhar', models.CharField(max_length=20)),
                ('Blood', models.CharField(max_length=5)),
                ('Email', models.CharField(max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Relation', models.CharField(max_length=15)),
                ('Gender', models.CharField(max_length=10)),
                ('Aadhar', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=50)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Applicants')),
            ],
        ),
        migrations.CreateModel(
            name='Health_Insurance',
            fields=[
                ('Insurance_Id', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=10)),
                ('Scheme', models.CharField(max_length=10)),
                ('Scheme_Amount', models.CharField(max_length=10)),
                ('App_Aadhar_Id', models.FileField(upload_to='Health/Documents')),
                ('Nom_Aadhar_Id', models.FileField(upload_to='Health/Documents')),
                ('Birth_Id', models.FileField(upload_to='Health/Documents')),
                ('image', models.ImageField(upload_to='Health/Images')),
                ('App_Status', models.CharField(default='Submitted', max_length=20)),
                ('Policy_Date', models.DateField(auto_now=True)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Applicants')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_Account', models.CharField(max_length=50)),
                ('Bank_Name', models.CharField(max_length=20)),
                ('Account_Number', models.CharField(max_length=50)),
                ('IFSC', models.CharField(max_length=50)),
                ('Branch', models.CharField(max_length=50)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Applicants')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Addr1', models.CharField(max_length=50)),
                ('Addr2', models.CharField(max_length=50)),
                ('Addr3', models.CharField(max_length=50)),
                ('Pin', models.CharField(max_length=15)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Applicants')),
            ],
        ),
    ]
