# Generated by Django 3.0.8 on 2021-03-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_life_childrens_applications_life_childrens_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Life_Employees_Applications',
            fields=[
                ('Appl_Id', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=10)),
                ('App_Name', models.CharField(max_length=50)),
                ('App_Father', models.CharField(max_length=50)),
                ('App_Mother', models.CharField(max_length=50)),
                ('App_DOB', models.DateField()),
                ('App_Gender', models.CharField(max_length=10)),
                ('App_Qual', models.CharField(max_length=10)),
                ('App_Mobile', models.CharField(max_length=15)),
                ('App_Aadhar', models.CharField(max_length=20)),
                ('App_Blood', models.CharField(max_length=5)),
                ('App_Email', models.CharField(max_length=50)),
                ('Addr1', models.CharField(max_length=50)),
                ('Addr2', models.CharField(max_length=50)),
                ('Addr3', models.CharField(max_length=50)),
                ('Pin', models.CharField(max_length=15)),
                ('Job_Type', models.CharField(max_length=15)),
                ('Company', models.CharField(max_length=25)),
                ('Company_Address', models.CharField(max_length=50)),
                ('Company_Pincode', models.CharField(max_length=50)),
                ('Nom_Name', models.CharField(max_length=50)),
                ('Nom_DOB', models.DateField()),
                ('Relation', models.CharField(max_length=15)),
                ('Nom_Gender', models.CharField(max_length=10)),
                ('Nom_Aadhar', models.CharField(max_length=20)),
                ('Nom_Mobile', models.CharField(max_length=15)),
                ('Nom_Email', models.CharField(max_length=50)),
                ('Bank_Account', models.CharField(max_length=50)),
                ('Bank_Name', models.CharField(max_length=20)),
                ('Account_Number', models.CharField(max_length=50)),
                ('IFSC', models.CharField(max_length=50)),
                ('Branch', models.CharField(max_length=50)),
                ('Scheme', models.CharField(max_length=10)),
                ('Scheme_Amount', models.CharField(max_length=10)),
                ('App_Aadhar_Id', models.FileField(upload_to='Life_Employees/Documents')),
                ('Nom_Aadhar_Id', models.FileField(upload_to='Life_Employees/Documents')),
                ('Employement_Id', models.FileField(upload_to='Life_Employees/Documents')),
                ('image', models.ImageField(upload_to='Life_Employees/Images')),
                ('Payment_Card', models.CharField(max_length=20)),
                ('Name_Card', models.CharField(max_length=50)),
                ('Paid_Amount', models.CharField(max_length=10)),
                ('App_Status', models.CharField(default='Submitted', max_length=20)),
                ('Now_Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='life_childrens_applications',
            name='Birth_Id',
            field=models.FileField(upload_to='Life_Childrens/Documents'),
        ),
        migrations.AlterField(
            model_name='life_childrens_applications',
            name='Nom_Aadhar_Id',
            field=models.FileField(upload_to='Life_Childrens/Documents'),
        ),
    ]
