# Generated by Django 3.0.8 on 2021-03-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210319_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Type', models.CharField(max_length=15)),
                ('Company', models.CharField(max_length=25)),
                ('Company_Address', models.CharField(max_length=50)),
                ('Company_Pincode', models.CharField(max_length=50)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Applicants')),
            ],
        ),
    ]
