# Generated by Django 3.0.8 on 2021-03-20 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Life_Employees_Insurance',
            fields=[
                ('Insurance_Id', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=10)),
                ('Scheme', models.CharField(max_length=10)),
                ('Scheme_Amount', models.CharField(max_length=10)),
                ('App_Aadhar_Id', models.FileField(upload_to='Life_Employees/Documents')),
                ('Nom_Aadhar_Id', models.FileField(upload_to='Life_Employees/Documents')),
                ('Employement_Id', models.FileField(upload_to='Life_Employees/Documents')),
                ('image', models.ImageField(upload_to='Life_Employees/Images')),
                ('App_Status', models.CharField(max_length=20)),
                ('Policy_Date', models.DateField(auto_now=True)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Applicants')),
            ],
        ),
    ]
