# Generated by Django 3.0.8 on 2021-03-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_appliances_applications_appliances_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Applications',
            fields=[
                ('Appl_Id', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=10)),
                ('App_Name', models.CharField(max_length=50)),
                ('App_DOB', models.DateField()),
                ('App_Gender', models.CharField(max_length=10)),
                ('App_Mobile', models.CharField(max_length=15)),
                ('App_Aadhar', models.CharField(max_length=20)),
                ('App_Email', models.CharField(max_length=50)),
                ('Addr1', models.CharField(max_length=50)),
                ('Addr2', models.CharField(max_length=50)),
                ('Addr3', models.CharField(max_length=50)),
                ('Pin', models.CharField(max_length=15)),
                ('Vehicle_Class', models.CharField(max_length=20)),
                ('Mnf_Date', models.DateField()),
                ('Chassis', models.CharField(max_length=30)),
                ('Engine', models.CharField(max_length=30)),
                ('Scheme', models.CharField(max_length=10)),
                ('Scheme_Amount', models.CharField(max_length=10)),
                ('App_Aadhar_Id', models.FileField(upload_to='Applications/Vehicle/Documents')),
                ('Rc_Id', models.FileField(upload_to='Applications/Vehicle/Documents')),
                ('image', models.ImageField(upload_to='Applications/Vehicle/Images')),
                ('Payment_Card', models.CharField(max_length=20)),
                ('Name_Card', models.CharField(max_length=50)),
                ('Paid_Amount', models.CharField(max_length=10)),
                ('App_Status', models.CharField(default='Submitted', max_length=20)),
                ('Now_Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Insurance',
            fields=[
                ('Insurance_Id', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=10)),
                ('Scheme', models.CharField(max_length=10)),
                ('Scheme_Amount', models.CharField(max_length=10)),
                ('App_Aadhar_Id', models.FileField(upload_to='Insurance/Vehicle/Documents')),
                ('Rc_Id', models.FileField(upload_to='Insurance/Vehicle/Documents')),
                ('image', models.ImageField(upload_to='Insurance/Vehicle/Images')),
                ('App_Status', models.CharField(default='Submitted', max_length=20)),
                ('Policy_Date', models.DateField()),
                ('Maturity_Date', models.DateField(null=True)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Applicants')),
            ],
        ),
    ]
