# Generated by Django 3.0.8 on 2021-03-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_vehicle_applications_vehicle_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Class', models.CharField(max_length=20)),
                ('Mnf_Date', models.DateField()),
                ('Chassis', models.CharField(max_length=30)),
                ('Engine', models.CharField(max_length=30)),
                ('Auth_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Applicants')),
            ],
        ),
    ]
