from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Applicants(models.Model):
    Appl_Id = models.TextField(primary_key=True,max_length=12)
    User = models.ForeignKey(User,on_delete=models.CASCADE)
    Name = models.CharField(max_length=50)
    Father = models.CharField(max_length=50)
    Mother = models.CharField(max_length=50)
    DOB = models.DateField()
    Gender = models.CharField(max_length=10)
    Qual = models.CharField(max_length=10)
    Mobile = models.CharField(max_length=15)
    Aadhar = models.CharField(max_length=20)
    Blood = models.CharField(max_length=5)
    Email = models.CharField(max_length=50)


class Address(models.Model):
    Auth_Id = models.ForeignKey(Applicants,on_delete=models.CASCADE)
    Addr1 = models.CharField(max_length=50)
    Addr2  = models.CharField(max_length=50)
    Addr3  = models.CharField(max_length=50)
    Pin = models.CharField(max_length=15)


class Account(models.Model):
    Auth_Id = models.ForeignKey(Applicants,on_delete=models.CASCADE)
    Category = models.CharField(max_length=10)
    Scheme = models.CharField(max_length=10)
    Scheme_Amount = models.CharField(max_length=50)
    Balance_Amount = models.CharField(max_length=50,null=True)
    last_Paid = models.DateField()


class Bank(models.Model):
    Auth_Id = models.ForeignKey(Applicants,on_delete=models.CASCADE)
    Bank_Account = models.CharField(max_length=50)
    Bank_Name = models.CharField(max_length=20)
    Account_Number = models.CharField(max_length=50)
    IFSC = models.CharField(max_length=50)
    Branch = models.CharField(max_length=50)


class Nominee(models.Model):
    Auth_Id = models.ForeignKey(Applicants,on_delete=models.CASCADE)
    Name = models.CharField(max_length=50)
    DOB = models.DateField()
    Relation = models.CharField(max_length=15)
    Gender = models.CharField(max_length=10)
    Aadhar = models.CharField(max_length=20)
    Mobile = models.CharField(max_length=15)
    Email = models.CharField(max_length=50)


class Employee(models.Model):
    Auth_Id = models.ForeignKey(Applicants,on_delete=models.CASCADE)
    Job_Type = models.CharField(max_length=15)
    Company = models.CharField(max_length=25)
    Company_Address = models.CharField(max_length=50)
    Company_Pincode = models.CharField(max_length=50)


class Health_Applications(models.Model):
    Appl_Id = models.TextField(primary_key=True,max_length=12)
    Category = models.CharField(max_length=10)
    App_Name = models.CharField(max_length=50)
    App_Father = models.CharField(max_length=50)
    App_Mother = models.CharField(max_length=50)
    App_DOB = models.DateField()
    App_Gender = models.CharField(max_length=10)
    App_Qual = models.CharField(max_length=10)
    App_Mobile = models.CharField(max_length=15)
    App_Aadhar = models.CharField(max_length=20)
    App_Blood = models.CharField(max_length=5)
    App_Email = models.CharField(max_length=50)
    Addr1 = models.CharField(max_length=50)
    Addr2  = models.CharField(max_length=50)
    Addr3  = models.CharField(max_length=50)
    Pin = models.CharField(max_length=15)
    Nom_Name = models.CharField(max_length=50)
    Nom_DOB = models.DateField()
    Relation = models.CharField(max_length=15)
    Nom_Gender = models.CharField(max_length=10)
    Nom_Aadhar = models.CharField(max_length=20)
    Nom_Mobile = models.CharField(max_length=15)
    Nom_Email = models.CharField(max_length=50)
    Bank_Account = models.CharField(max_length=50)
    Bank_Name = models.CharField(max_length=20)
    Account_Number = models.CharField(max_length=50)
    IFSC = models.CharField(max_length=50)
    Branch = models.CharField(max_length=50)
    Scheme = models.CharField(max_length=10)
    Scheme_Amount = models.CharField(max_length=10)
    App_Aadhar_Id = models.FileField(upload_to='Applications/Health/Documents')
    Nom_Aadhar_Id = models.FileField(upload_to='Applications/Health/Documents')
    Birth_Id = models.FileField(upload_to='Applications/Health/Documents')
    image = models.ImageField(upload_to='Applications/Health/Images')
    Payment_Card = models.CharField(max_length=20)
    Name_Card = models.CharField(max_length=50)
    Paid_Amount = models.CharField(max_length=10)
    App_Status=models.CharField(max_length=20,default='Submitted')
    Now_Date=models.DateField(auto_now=True)


class Health_Insurance(models.Model):
    Insurance_Id = models.TextField(primary_key=True,max_length=12)
    Auth_Id = models.ForeignKey(Applicants,on_delete=models.CASCADE)
    Category = models.CharField(max_length=10)
    Scheme = models.CharField(max_length=10)
    Scheme_Amount = models.CharField(max_length=10)
    App_Aadhar_Id = models.FileField(upload_to='Insurance/Health/Documents')
    Nom_Aadhar_Id = models.FileField(upload_to='Insurance/Health/Documents')
    Birth_Id = models.FileField(upload_to='Insurance/Health/Documents')
    image = models.ImageField(upload_to='Insurance/Health/Images')
    App_Status=models.CharField(max_length=20,default='Submitted')
    Policy_Date=models.DateField()
    Maturity_Date=models.DateField(null=True)


class Appliances_Applications(models.Model):
    Appl_Id = models.TextField(primary_key=True,max_length=12)
    Category = models.CharField(max_length=10)
    App_Name = models.CharField(max_length=50)
    App_DOB = models.DateField()
    App_Gender = models.CharField(max_length=10)
    App_Mobile = models.CharField(max_length=15)
    App_Aadhar = models.CharField(max_length=20)
    App_Email = models.CharField(max_length=50)
    Addr1 = models.CharField(max_length=50)
    Addr2  = models.CharField(max_length=50)
    Addr3  = models.CharField(max_length=50)
    Pin = models.CharField(max_length=15)
    Scheme = models.CharField(max_length=10)
    Scheme_Amount = models.CharField(max_length=10)
    App_Aadhar_Id = models.FileField(upload_to='Applications/Appliances/Documents')
    Addr_Id = models.FileField(upload_to='Applications/Appliances/Documents')
    Payment_Card = models.CharField(max_length=20)
    Name_Card = models.CharField(max_length=50)
    Paid_Amount = models.CharField(max_length=10)
    App_Status=models.CharField(max_length=20,default='Submitted')
    Now_Date=models.DateField(auto_now=True)


class Appliances_Insurance(models.Model):
    Insurance_Id = models.TextField(primary_key=True,max_length=12)
    Auth_Id = models.ForeignKey(Applicants,on_delete=models.CASCADE)
    Category = models.CharField(max_length=10)
    Scheme = models.CharField(max_length=10)
    Scheme_Amount = models.CharField(max_length=10)
    App_Aadhar_Id = models.FileField(upload_to='Insurance/Appliances/Documents')
    Addr_Id = models.FileField(upload_to='Insurance/Appliances/Documents')
    App_Status=models.CharField(max_length=20,default='Submitted')
    Policy_Date=models.DateField()
    Maturity_Date=models.DateField(null=True)


class Vehicle_Applications(models.Model):
    Appl_Id = models.TextField(primary_key=True,max_length=12)
    Category = models.CharField(max_length=10)
    App_Name = models.CharField(max_length=50)
    App_DOB = models.DateField()
    App_Gender = models.CharField(max_length=10)
    App_Mobile = models.CharField(max_length=15)
    App_Aadhar = models.CharField(max_length=20)
    App_Email = models.CharField(max_length=50)
    Addr1 = models.CharField(max_length=50)
    Addr2  = models.CharField(max_length=50)
    Addr3  = models.CharField(max_length=50)
    Pin = models.CharField(max_length=15)
    Vehicle_Class = models.CharField(max_length=20)
    Mnf_Date=models.DateField()
    Chassis = models.CharField(max_length=30)
    Engine = models.CharField(max_length=30)
    Scheme = models.CharField(max_length=10)
    Scheme_Amount = models.CharField(max_length=10)
    App_Aadhar_Id = models.FileField(upload_to='Applications/Vehicle/Documents')
    Rc_Id = models.FileField(upload_to='Applications/Vehicle/Documents')
    image = models.ImageField(upload_to='Applications/Vehicle/Images')
    Payment_Card = models.CharField(max_length=20)
    Name_Card = models.CharField(max_length=50)
    Paid_Amount = models.CharField(max_length=10)
    App_Status=models.CharField(max_length=20,default='Submitted')
    Now_Date=models.DateField(auto_now=True)


class Vehicle_Insurance(models.Model):
    Insurance_Id = models.TextField(primary_key=True,max_length=12)
    Auth_Id = models.ForeignKey(Applicants,on_delete=models.CASCADE)
    Category = models.CharField(max_length=10)
    Scheme = models.CharField(max_length=10)
    Scheme_Amount = models.CharField(max_length=10)
    App_Aadhar_Id = models.FileField(upload_to='Insurance/Vehicle/Documents')
    Rc_Id = models.FileField(upload_to='Insurance/Vehicle/Documents')
    image = models.ImageField(upload_to='Insurance/Vehicle/Images')
    App_Status=models.CharField(max_length=20,default='Submitted')
    Policy_Date=models.DateField()
    Maturity_Date=models.DateField(null=True)


class Vehicle(models.Model):
    Auth_Id = models.ForeignKey(Applicants,on_delete=models.CASCADE)
    Vehicle_Class = models.CharField(max_length=20)
    Mnf_Date=models.DateField()
    Chassis = models.CharField(max_length=30)
    Engine = models.CharField(max_length=30)


class Life_Childrens_Applications(models.Model):
    Appl_Id = models.TextField(primary_key=True,max_length=12)
    Category = models.CharField(max_length=10)
    App_Name = models.CharField(max_length=50)
    App_Father = models.CharField(max_length=50)
    App_Mother = models.CharField(max_length=50)
    App_DOB = models.DateField()
    App_Gender = models.CharField(max_length=10)
    App_Mobile = models.CharField(max_length=15)
    App_Email = models.CharField(max_length=50)
    Addr1 = models.CharField(max_length=50)
    Addr2  = models.CharField(max_length=50)
    Addr3  = models.CharField(max_length=50)
    Pin = models.CharField(max_length=15)
    Nom_Name = models.CharField(max_length=50)
    Nom_DOB = models.DateField()
    Relation = models.CharField(max_length=15)
    Nom_Gender = models.CharField(max_length=10)
    Nom_Aadhar = models.CharField(max_length=20)
    Nom_Mobile = models.CharField(max_length=15)
    Nom_Email = models.CharField(max_length=50)
    Scheme = models.CharField(max_length=10)
    Scheme_Amount = models.CharField(max_length=10)
    Nom_Aadhar_Id = models.FileField(upload_to='Applications/Life_Childrens/Documents')
    Birth_Id = models.FileField(upload_to='Applications/Life_Childrens/Documents')
    Payment_Card = models.CharField(max_length=20)
    Name_Card = models.CharField(max_length=50)
    Paid_Amount = models.CharField(max_length=10)
    App_Status=models.CharField(max_length=20,default='Submitted')
    Now_Date=models.DateField(auto_now=True)


class Life_Childrens_Insurance(models.Model):
    Insurance_Id = models.TextField(primary_key=True,max_length=12)
    Auth_Id = models.ForeignKey(Applicants,on_delete=models.CASCADE)
    Category = models.CharField(max_length=10)
    Scheme = models.CharField(max_length=10)
    Scheme_Amount = models.CharField(max_length=10)
    Nom_Aadhar_Id = models.FileField(upload_to='Insurance/Life_Childrens/Documents')
    Birth_Id = models.FileField(upload_to='Insurance/Life_Childrens/Documents')
    App_Status=models.CharField(max_length=20)
    Policy_Date=models.DateField()
    Maturity_Date=models.DateField(null=True)


class Life_Employees_Applications(models.Model):
    Appl_Id = models.TextField(primary_key=True,max_length=12)
    Category = models.CharField(max_length=10)
    App_Name = models.CharField(max_length=50)
    App_Father = models.CharField(max_length=50)
    App_Mother = models.CharField(max_length=50)
    App_DOB = models.DateField()
    App_Gender = models.CharField(max_length=10)
    App_Qual = models.CharField(max_length=10)
    App_Mobile = models.CharField(max_length=15)
    App_Aadhar = models.CharField(max_length=20)
    App_Blood = models.CharField(max_length=5)
    App_Email = models.CharField(max_length=50)
    Addr1 = models.CharField(max_length=50)
    Addr2  = models.CharField(max_length=50)
    Addr3  = models.CharField(max_length=50)
    Pin = models.CharField(max_length=15)
    Job_Type = models.CharField(max_length=15)
    Company = models.CharField(max_length=25)
    Company_Address = models.CharField(max_length=50)
    Company_Pincode = models.CharField(max_length=50)
    Nom_Name = models.CharField(max_length=50)
    Nom_DOB = models.DateField()
    Relation = models.CharField(max_length=15)
    Nom_Gender = models.CharField(max_length=10)
    Nom_Aadhar = models.CharField(max_length=20)
    Nom_Mobile = models.CharField(max_length=15)
    Nom_Email = models.CharField(max_length=50)
    Bank_Account = models.CharField(max_length=50)
    Bank_Name = models.CharField(max_length=20)
    Account_Number = models.CharField(max_length=50)
    IFSC = models.CharField(max_length=50)
    Branch = models.CharField(max_length=50)
    Scheme = models.CharField(max_length=10)
    Scheme_Amount = models.CharField(max_length=10)
    App_Aadhar_Id = models.FileField(upload_to='Applications/Life_Employees/Documents')
    Nom_Aadhar_Id = models.FileField(upload_to='Applications/Life_Employees/Documents')
    Employement_Id = models.FileField(upload_to='Applications/Life_Employees/Documents')
    image = models.ImageField(upload_to='Applications/Life_Employees/Images')
    Payment_Card = models.CharField(max_length=20)
    Name_Card = models.CharField(max_length=50)
    Paid_Amount = models.CharField(max_length=10)
    App_Status=models.CharField(max_length=20,default='Submitted')
    Now_Date=models.DateField(auto_now=True)


class Life_Employees_Insurance(models.Model):
    Insurance_Id = models.TextField(primary_key=True,max_length=12)
    Auth_Id = models.ForeignKey(Applicants,on_delete=models.CASCADE)
    Category = models.CharField(max_length=10)
    Scheme = models.CharField(max_length=10)
    Scheme_Amount = models.CharField(max_length=10)
    App_Aadhar_Id = models.FileField(upload_to='Insurance/Life_Employees/Documents')
    Nom_Aadhar_Id = models.FileField(upload_to='Insurance/Life_Employees/Documents')
    Employement_Id = models.FileField(upload_to='Insurance/Life_Employees/Documents')
    image = models.ImageField(upload_to='Insurance/Life_Employees/Images')
    App_Status=models.CharField(max_length=20)
    Policy_Date=models.DateField()
    Maturity_Date=models.DateField(null=True)